
[project]
name = "TelegramMessenger"
version = "1.0.0"
description = "TelegramMessenger helps send telegram messages."
readme = "README.md"
authors = [{ name = "Poushsaat" }]
license = { file = "LICENSE" }
dependencies = [
    "requests"
]
