name: Deploy
on:
  push:
    branches:
      - main
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.PYPI_TOKEN }}
    environment:
      name: pypi
      url: https://pypi.org/p/TelegramMessenger
    permissions:
      id-token: write
      
    steps:
    # retrieve your distributions here
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
